version: '3.8'

services:
  spark-master:
    image: custom-spark:latest
    hostname: spark-master
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker-1:
    image: custom-spark:latest
    hostname: spark-worker-1
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=15G
      - SPARK_WORKER_CORES=8
    depends_on:
      - spark-master

  spark-worker-2:
    image: custom-spark:latest
    hostname: spark-worker-2
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=15G
      - SPARK_WORKER_CORES=8
    depends_on:
      - spark-master
